// Build Visage into self-contained files.
//   node build.mjs            runner + server bundle + editor UI in build/
//   node build.mjs --runner   only the exported-workflow runner (used by tests)
//   node build.mjs --plugin   everything above, assembled as a Claude Code / Codex plugin in dist/
import { execSync } from 'node:child_process'
import { cpSync, existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { dirname, join, relative, sep } from 'node:path'
import { fileURLToPath } from 'node:url'
import { build } from 'esbuild'
import { zipSync } from 'fflate'

const root = dirname(fileURLToPath(import.meta.url))
const out = join(root, 'build')
const frontend = join(root, '..', 'frontend')
const args = new Set(process.argv.slice(2))
const { version } = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'))

const common = { bundle: true, platform: 'node', target: 'node20', format: 'esm', legalComments: 'none', logLevel: 'warning' }

async function buildRunner() {
  await build({ ...common, entryPoints: [join(root, 'src/runner/flow.ts')], outfile: join(out, 'flow.mjs'), banner: { js: '#!/usr/bin/env node' } })
}

/** Short commit hash of the source being built, with -dirty when there are uncommitted changes. */
function buildId() {
  try {
    const hash = execSync('git rev-parse --short HEAD', { cwd: root, stdio: ['ignore', 'pipe', 'ignore'] }).toString().trim()
    const dirty = execSync('git status --porcelain', { cwd: root, stdio: ['ignore', 'pipe', 'ignore'] }).toString().trim()
    return dirty ? `${hash}-dirty` : hash
  } catch {
    return 'unknown'
  }
}

/** src/version.ts is generated (and ignored by Git) so building never changes tracked files. */
function writeVersion() {
  writeFileSync(join(root, 'src/version.ts'), `// Generated by build.mjs from package.json and Git; do not edit.\nexport const VERSION = '${version}'\nexport const BUILD = '${buildId()}'\n`)
}

async function buildServer() {
  await build({
    ...common,
    entryPoints: [join(root, 'src/main.ts')],
    outfile: join(out, 'visage.js'),
    // Some bundled dependencies are CommonJS and call require().
    banner: { js: "import { createRequire as __createRequire } from 'node:module';\nconst require = __createRequire(import.meta.url);" },
    minify: true,
  })
}

function buildUi() {
  execSync('npm run build', { cwd: frontend, stdio: 'inherit' })
  rmSync(join(out, 'ui'), { recursive: true, force: true })
  cpSync(join(frontend, 'dist'), join(out, 'ui'), { recursive: true })
}

// The Skill, its references and the README come from docs/harness, the single source of the harness documentation.
const harnessDocs = join(root, '..', 'docs', 'harness')

function assemblePlugin() {
  const dist = join(root, 'dist')
  const plugin = join(dist, 'visage')
  rmSync(plugin, { recursive: true, force: true })
  mkdirSync(join(plugin, 'server'), { recursive: true })
  cpSync(join(out, 'visage.js'), join(plugin, 'server', 'visage.js'))
  cpSync(join(out, 'flow.mjs'), join(plugin, 'server', 'flow.mjs'))
  cpSync(join(out, 'ui'), join(plugin, 'server', 'ui'), { recursive: true })
  mkdirSync(join(plugin, 'skills', 'visage'), { recursive: true })
  cpSync(join(harnessDocs, 'SKILL.md'), join(plugin, 'skills', 'visage', 'SKILL.md'))
  cpSync(join(harnessDocs, 'references'), join(plugin, 'skills', 'visage', 'references'), { recursive: true })
  cpSync(join(root, '..', 'LICENSE'), join(plugin, 'LICENSE'))
  const description = 'Visual editor and MCP server for state-machine workflows of agent Skills, exportable as Claude Code and Codex plugins.'
  const manifest = { name: 'visage', version, description, author: { name: 'Ilexis Tools' }, license: 'MIT', repository: 'https://github.com/ilexistools/Visage', keywords: ['workflow', 'state-machine', 'skills', 'mcp'] }
  const json = value => JSON.stringify(value, null, 2) + '\n'
  mkdirSync(join(plugin, '.claude-plugin'))
  writeFileSync(join(plugin, '.claude-plugin', 'plugin.json'), json(manifest))
  writeFileSync(join(plugin, '.mcp.json'), json({ mcpServers: { visage: { command: 'node', args: ['${CLAUDE_PLUGIN_ROOT}/server/visage.js', '--stdio'] } } }))
  mkdirSync(join(plugin, '.codex-plugin'))
  writeFileSync(join(plugin, '.codex-plugin', 'plugin.json'), json({
    ...manifest, skills: './skills/', mcpServers: './.codex-mcp.json',
    interface: {
      displayName: 'Visage', shortDescription: 'Design and export state-machine workflows of Skills', longDescription: description,
      developerName: 'Ilexis Tools', category: 'Productivity', capabilities: ['Interactive', 'Write'],
      defaultPrompt: ['Open the Visage editor', 'Create a Visage workflow for this process'],
    },
  }))
  writeFileSync(join(plugin, '.codex-mcp.json'), json({ mcpServers: { visage: { command: 'node', args: ['./server/visage.js', '--stdio'], cwd: '.', startup_timeout_sec: 20 } } }))
  // Links in the README point into the Skill folder inside the plugin.
  const readme = readFileSync(join(harnessDocs, 'README.md'), 'utf8').replace(/\]\((SKILL\.md|references\/)/g, '](skills/visage/$1')
  writeFileSync(join(plugin, 'README.md'), `${readme}\n---\nVisage ${version}\n`)
  const files = {}
  const walk = folder => {
    for (const entry of readdirSync(folder, { withFileTypes: true })) {
      const path = join(folder, entry.name)
      if (entry.isDirectory()) walk(path)
      else files[`visage/${relative(plugin, path).split(sep).join('/')}`] = readFileSync(path)
    }
  }
  walk(plugin)
  const archive = join(dist, `visage-${version}.zip`)
  writeFileSync(archive, zipSync(files, { level: 9 }))
  console.log(`Plugin: ${plugin}\nZip:    ${archive}`)
}

writeVersion()
if (args.has('--version-only')) process.exit(0)
mkdirSync(out, { recursive: true })
await buildRunner()
if (!args.has('--runner')) {
  await buildServer()
  if (!existsSync(join(out, 'ui')) || !args.has('--skip-ui')) buildUi()
  if (args.has('--plugin')) assemblePlugin()
}
